---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: test-couchbase-source
  namespace: confluent
spec:
  class: "com.couchbase.connect.kafka.CouchbaseSourceConnector"
  taskMax: 1
  connectClusterRef:
    name: connect-demo
  configs:
    couchbase.topic: "test-default"
    couchbase.seed.nodes: "Node Host Name"
    couchbase.bootstrap.timeout": "10s"
    couchbase.bucket: "Bucket Name"
    couchbase.username: "Cluster Usr"
    couchbase.password: "Cluster Pss"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    couchbase.source.handler: "com.couchbase.connect.kafka.handler.source.RawJsonSourceHandler"
    value.converter: "org.apache.kafka.connect.converters.ByteArrayConverter"
    couchbase.event.filter: "com.couchbase.connect.kafka.filter.AllPassFilter"
    couchbase.stream.from: "SAVED_OFFSET_OR_BEGINNING"
    couchbase.compression: "ENABLED"
    couchbase.flow.control.buffer: "16m"
    couchbase.persistence.polling.interval: "100ms"
    couchbase.collections: "scope name.collection name"
    couchbase.enable.tls: "true"
    value.converter.schema.registry.url: "https://xxxx-xxxxx.us-east-2.aws.confluent.cloud"
    value.converter.basic.auth.credentials.source: "USER_INFO"
    value.converter.schema.registry.basic.auth.user.info: "SR API Key:SR API Secret"
