---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: datagen-pageview
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  connectClusterRef:
    name: connect-demo
  configs:
    kafka.topic: "pageviews"
    quickstart: "pageviews"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "true"
    max.interval: "100"
    iterations: "10000000"
    value.converter.schema.registry.url: "https://xxxx-xxxxx.us-east-2.aws.confluent.cloud"
    value.converter.basic.auth.credentials.source: "USER_INFO"
    value.converter.schema.registry.basic.auth.user.info: "SR API Key:SR API Secret"
